SELECTOR_FLAT_C =       0x08
SELECTOR_FLAT_RW=       0x10
SELECTOR_CGATE  =       0x20
SELECTOR_TSS    =       0x28

DA_386CGATE     =       0x8c

PCB_EAX         =       44
PCB_RET_ADDR    =       48
PCB_SS          =       72
PCB_SEL_LDT     =       72

TSS_ESP0        =       4

EOI             =       0x20

ICRM            =       0x20
IMRM            =       0x21
ICRS            =       0xa0
IMRS            =       0xa1
